services:

  # App itself
  api:
    image: ghcr.io/a-lehmann-elektro-ag/webshop-restful:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      MONGODB_CONNECT_STRING: ${MONGODB_CONNECT_DOCKER}

  # Mongo DB
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
