name: CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGODB_CONNECT_STRING: ${{ secrets.MONGODB_CONNECT_STRING }}
      MONGODB_CONNECT_DOCKER: ${{ secrets.MONGODB_CONNECT_DOCKER }}
      MONGODB_ADMINUSERNAME: ${{ secrets.MONGODB_ADMINUSERNAME }}
      MONGODB_ADMINPASSWORD: ${{ secrets.MONGODB_ADMINPASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Compose services
        run: docker-compose -f docker-compose.yml build

      - name: Push to GitHub Container Registry
        run: |
          docker-compose push

